<?php
namespace Impala;
/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface ImpalaHiveServer2ServiceIf extends \Apache\Hadoop\Hive\Cli\TCLIServiceIf {
}

class ImpalaHiveServer2ServiceClient extends \Apache\Hadoop\Hive\Cli\TCLIServiceClient implements \Impala\ImpalaHiveServer2ServiceIf {
  public function __construct($input, $output=null) {
    parent::__construct($input, $output);
  }

}

// HELPER FUNCTIONS AND STRUCTURES


